### PR TITLE
Update benchmark

### PR DESCRIPTION
**Pull request by thiagodp**
- Change to use the latest version of each library
- Add library `nopt`
- Add library `getopts` in order to compare the current implementation to the prior version
- Change to parse more argument types

### CODE REVIEW

**Comment by thiagodp** [comment]
This update doesn't touch the source code under code coverage (so `codecov`'s feedback can be ignored).

**Comment by jorgebucaran** [comment]
@thiagodp If you can leave only the changes to `package.json` so we always pull the latest (just change `latest` to `*`) version of each package I'm good. You may keep `nopt` as well, but please make sure it produces the same result as everyone else for the argv we're currently using.

**Comment by thiagodp** [comment]
@jorgebucaran Done 👍

**Comment by jorgebucaran** [comment]
I mean, leave only the changes to `package.json`. I'm not interested in the other changes.

**Comment by jorgebucaran** [comment]
@thiagodp It's been a while. I'm currently working on a new minor version that uses ES modules, I'll be modernizing the benchmarks, grabbing the latest dependencies, and moving files around. Thank you anyway! 💯

**Comment by jorgebucaran** [comment]
It's been a while. I'm currently working on a new minor version that uses ES modules. I'll be modernizing the benchmarks, grabbing the latest dependencies, and moving files around. Thank you anyway! 💯

**Pull request closed without merging**
